---
- name: Configure system
  hosts: all
  roles:
    - install_utils
    - configure_bash
    - install_i3
    - configure_git
    - install_docker
    - quick_run
    - install_python_tools
    - install_nodejs
    - install_infrastructure_tools
