---
- name: Add NodeSource GPG keyring
  ansible.builtin.apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    state: present
  become: true

- name: Add NodeSource repo
  ansible.builtin.apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ install_nodejs_major_version }}.x nodistro main"
    state: present
    filename: nodesource
  become: true

- name: Install node
  ansible.builtin.apt:
    name: nodejs
    state: present
    update_cache: true
  become: true
