---
- name: Ensure autoload directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.vim/autoload"
    state: directory
    mode: "755"

- name: Download vim-plug plugin manager
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_env.HOME }}/.vim/autoload/plug.vim"
    mode: "644"
    force: false

- name: Copy vim configuration file
  ansible.builtin.copy:
    src: vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"
    mode: "644"
    backup: true
