---
- name: Copy bash configuration file
  ansible.builtin.copy:
    src: ".bashrc_local"
    dest: "{{ ansible_env.HOME }}/.bashrc_local"
    mode: +rw

- name: Ensure .bashrc sources .bashrc_local
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'source ~/.bashrc_local'
    state: present

- name: Copy bash aliases file
  ansible.builtin.copy:
    src: ".bash_aliases"
    dest: "{{ ansible_env.HOME }}/.bash_aliases"
    mode: +rw
