---
- name: Add Kubernetes apt key
  become: true
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v{{ install_infrastructure_tools_kubectl_version }}/deb/Release.key
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    state: present

- name: Add Kubernetes apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: >
      deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg]
      https://pkgs.k8s.io/core:/stable:/v{{ install_infrastructure_tools_kubectl_version }}/deb/ /
    filename: kubernetes
    state: present
    mode: "644"

- name: Install kubectl
  become: true
  ansible.builtin.apt:
    name: kubectl
    state: present
    update_cache: true
