---
- name: Add HashiCorp GPG key
  become: true
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add HashiCorp repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release | lower }} main"
    state: present
    filename: hashicorp
    mode: "644"

- name: Install terraform
  become: true
  ansible.builtin.apt:
    name: terraform
    state: present
    update_cache: true
